"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { SlidersHorizontal,Save,RotateCcw,GitBranch,Loader2 } from "lucide-react";
import { TOOLS } from "@/lib/tool-definitions";
import type { ProfileSnapshot,WorkflowProfile } from "@/lib/rag/profile";
import { PremiumSelect } from "@/components/premium-select";
import { NumberField } from "@/components/number-field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
type Info={snapshot:ProfileSnapshot;history:Array<{revision:number;hash:string;createdAt:string}>;dag:{sourceIds:string[]};engineering:Array<{id:string;nodes:Array<{id:string;label:string;dependsOn:string[]}>}>;catalog:Array<{id:string;name:string}>;fixedPolicy:string};
export function SpecializationWorkspace(){
 const [tool,setTool]=useState("enforceability"),[info,setInfo]=useState<Info|null>(null),[draft,setDraft]=useState<WorkflowProfile|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[compare,setCompare]=useState<ProfileSnapshot|null>(null);
 const [requiredText,setRequiredText]=useState("");
 const refresh=useCallback(async()=>{const response=await fetch(`/api/specialization?tool=${tool}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"تعذّر تحميل التخصص.");setInfo(data);setDraft(data.snapshot.profile);setRequiredText(data.snapshot.profile.requiredUnitIds.join("\n"));setCompare(null);},[tool]);
 useEffect(()=>{const timer=setTimeout(()=>{refresh().catch(e=>setMessage(e.message));},0);return()=>clearTimeout(timer);},[refresh]);
 function edit<K extends keyof WorkflowProfile>(key:K,value:WorkflowProfile[K]){setDraft(p=>p?{...p,[key]:value}:p);}
 async function save(){if(!draft||!info)return;setBusy(true);setMessage("");try{const response=await fetch("/api/specialization",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({toolSlug:tool,expectedRevision:info.snapshot.revision,profile:draft})});const data=await response.json();if(!response.ok)throw new Error(data.error||"الحفظ فشل.");await refresh();setMessage(`اتحفظ الإصدار ${data.snapshot.revision}. النتائج السابقة تحتاج إعادة تشغيل قبل اعتمادها.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function historical(revision:number){setBusy(true);try{const response=await fetch(`/api/specialization?tool=${tool}&revision=${revision}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setCompare(data.snapshot);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const fields=[{key:"extractionInstructions",title:"تعليمات استخراج الوقائع",hint:"إيه اللي لازم يتلقط من المستند؟ حدّد البنود أو الأحداث أو الأطراف المهمة، واطلب نسبة كل قول لصاحبه."},{key:"analysisInstructions",title:"تعليمات التحليل المتخصص",hint:"اكتب طريقة المراجعة وأسئلة التخصص والاستثناءات اللي لازم تتفحص. التعليمات ليست مصدرًا قانونيًا."},{key:"verificationInstructions",title:"تعليمات المراجع المستقل",hint:"حدّد الأخطاء اللي المراجع يدور عليها، وحالات النقص والتعارض اللي تستلزم الامتناع."}] as const;
 return <div className="page-wrap knowledge-page"><section className="tool-titlebar"><div className="tool-title-icon"><SlidersHorizontal/></div><div><p className="eyebrow">SPECIALIZATION · VERSIONED CONTEXT</p><h1>تطوير التخصص وطريقة المراجعة</h1><p>عدّل تركيز كل أداة وتعليماتها، مع سجل إصدارات واضح وبوابات أدلة ثابتة.</p></div></section>
 <section className="workspace-card"><label className="field-label"><span>اختار الأداة اللي عايز تطورها</span><PremiumSelect value={tool} disabled={busy||!info} onValueChange={v=>{setInfo(null);setDraft(null);setTool(v);setMessage("");}} options={TOOLS.map(t=>({value:t.slug,label:t.shortName}))} ariaLabel="الأداة المطلوب تطويرها" placeholder="اختار الأداة"/></label><p>كل أداة لها تعليمات مستقلة. احفظ تعديلاتك قبل تغيير الأداة. تعديل التعليمات يغيّر التوجيه، ولا يدرّب أوزان الموديل.</p><Link className="secondary-action" href="/knowledge">افتح النصوص القانونية وملف الذاكرة</Link></section>
 {!info||!draft?<div className="empty-state"><Loader2 className="spin"/>بنحمّل التخصص...</div>:<>
 <div className="workspace-grid specialization-grid"><section className="workspace-card"><div className="panel-heading"><span className="panel-step">01</span><div><h2>تعليمات التخصص</h2><p>الإصدار الحالي {info.snapshot.revision} · <bdi>{info.snapshot.hash.slice(0,12)}</bdi></p></div></div>
 <label className="field-label"><span>اسم التخصص</span><Input value={draft.label} onChange={e=>edit("label",e.target.value)} maxLength={120}/></label>
 <label className="field-label"><span>مواضيع يركز عليها البحث</span><Textarea value={draft.searchFocus} onChange={e=>edit("searchFocus",e.target.value)} maxLength={1500} placeholder="اكتب المواضيع والأسئلة المرتبطة بملفاتك؛ لا تضف تعليمات لتجاوز المصادر."/></label>
 {fields.map(field=><label className="field-label" key={field.key}><span>{field.title}</span><small>{field.hint}</small><Textarea className="specialization-prompt" value={draft[field.key]} onChange={e=>edit(field.key,e.target.value)} maxLength={field.key==="analysisInstructions"?8000:5000} placeholder="تركها فارغة يستخدم تعليمات الأداة الأساسية."/><small>{draft[field.key].length} حرف</small></label>)}
 </section><section className="workspace-card"><div className="panel-heading"><span className="panel-step">02</span><div><h2>حدود السياق والمصادر</h2><p>قائمة التخصص تضيق مصادر المكتب المسموحة، ولا توسعها.</p></div></div>
 <div className="memory-sources">{info.catalog.filter(s=>info.dag.sourceIds.includes(s.id)).map(source=><label className="memory-consent" key={source.id}><input type="checkbox" checked={draft.sourceIds.includes(source.id)} onChange={e=>edit("sourceIds",e.target.checked?[...draft.sourceIds,source.id]:draft.sourceIds.filter(id=>id!==source.id))}/>{source.name}</label>)}</div>
 <label className="field-label"><span>معرفات نصوص لازم تكون موجودة في كل تحليل</span><Textarea value={requiredText} onChange={e=>{setRequiredText(e.target.value);edit("requiredUnitIds",e.target.value.split(/\s+/).filter(Boolean));}} placeholder="معرف واحد لكل سطر، مثل مادة أساسية والاستثناء المرتبط بها."/><small>انسخ المعرف من الذاكرة القانونية. النص المطلوب يدخل السياق مع نتائج البحث؛ سحبه أو خروجه من السريان يوقف التشغيل. بحد عدد النصوص المحدد لإعادة الترتيب.</small></label>
 <label className="field-label"><span>أقصى حجم سياق لكل مكالمة — بالحروف</span><NumberField label="ميزانية السياق" value={draft.maxContextChars} min={20000} max={220000} step={1000} onValueChange={v=>edit("maxContextChars",v)}/><small>حد حروف تشغيلي؛ لا يساوي عدد رموز الموديل. لو السياق تجاوز الحد يتوقف الطلب بوضوح.</small></label>
 <details className="fixed-policy"><summary>القواعد الثابتة وحالات الامتناع</summary><pre>{info.fixedPolicy}</pre></details>
 <label className="field-label"><span>اسم مراجع التعديل</span><Input value={draft.reviewedBy} onChange={e=>edit("reviewedBy",e.target.value)} maxLength={100}/></label>
 <label className="field-label"><span>ليه بنغيّر التخصص؟</span><Textarea value={draft.changeNote} onChange={e=>edit("changeNote",e.target.value)} maxLength={500}/></label>
 <Button className="run-button" disabled={busy} onClick={save}>{busy?<Loader2 className="spin"/>:<Save/>}حفظ إصدار جديد وتشغيله في المرة الجاية</Button>
 <p className="ssh-help">نفس الإصدار يتبعت لسيرفر التنفيذ لو اخترته. اعتماد النتائج يعيد فحص الإصدار؛ تعديل التعليمات لا يحدّث تقارير قديمة بصمت.</p>
 </section></div>
 <section className="workspace-card memory-import"><h2>الإصدارات السابقة</h2><p>فتح إصدار سابق يعرض المقارنة. استعادته تنشئ إصدارًا جديدًا عند الحفظ وتحفظ التاريخ القديم.</p><div className="memory-actions"><Button variant="outline" disabled={busy} onClick={()=>historical(0)}>التخصص الأساسي</Button>{info.history.map(h=><Button variant="outline" disabled={busy} key={h.revision} onClick={()=>historical(h.revision)}>إصدار {h.revision}</Button>)}</div>
 {compare&&<div className="profile-compare"><h3>مقارنة مع الإصدار {compare.revision}</h3>{["label","searchFocus",...fields.map(f=>f.key),"sourceIds","requiredUnitIds","maxContextChars"] .filter(k=>JSON.stringify(compare.profile[k as keyof WorkflowProfile])!==JSON.stringify(draft[k as keyof WorkflowProfile])).map(key=><details key={key}><summary>{({label:"الاسم",searchFocus:"تركيز البحث",sourceIds:"المصادر",requiredUnitIds:"النصوص الإلزامية",maxContextChars:"الميزانية",extractionInstructions:"الاستخراج",analysisInstructions:"التحليل",verificationInstructions:"المراجعة"} as Record<string,string>)[key]}</summary><div className="field-pair"><div><strong>الإصدار السابق</strong><pre>{String(compare.profile[key as keyof WorkflowProfile])}</pre></div><div><strong>التعديل الحالي</strong><pre>{String(draft[key as keyof WorkflowProfile])}</pre></div></div></details>)}<Button variant="outline" onClick={()=>{setRequiredText(compare.profile.requiredUnitIds.join("\n"));setDraft({...compare.profile,reviewedBy:draft.reviewedBy,changeNote:`استعادة تعليمات الإصدار ${compare.revision}`});setMessage("اتحمّلت التعليمات السابقة للمراجعة. اضغط حفظ لتسجيل إصدار جديد.");}}><RotateCcw/>استخدم النسخة دي كمسودة تعديل</Button></div>}
 </section>
 <section className="memory-dags"><h2><GitBranch/>مسارات تجهيز الذاكرة والسياق</h2>{info.engineering.map(graph=><article className="workspace-card" key={graph.id}><h3>{graph.id==="memory"?"تجهيز الذاكرة القانونية":"تجهيز سياق التحليل"}</h3><ol>{graph.nodes.map(n=><li key={n.id}><strong>{n.label}</strong><small>{n.dependsOn.length?"تعمل بعد اعتماد نتيجة الخطوة السابقة":"تبدأ بتحقق مستقل"}</small></li>)}</ol></article>)}</section>
 </>}{message&&<div className="settings-message memory-message" role="status">{message}</div>}</div>;
}
