import "server-only";
import { getDb } from "@/db";

export type VisitorRow = { id:string; firstSeenAt:string; lastSeenAt:string; visitCount:number; guideCompletedAt:string|null; termsVersion:string|null; termsAcceptedAt:string|null };
export type ProviderRow = { id:string; userId:string; label:string; provider:string; model:string; baseUrl:string; apiKeyCiphertext:string; apiKeyIv:string; createdAt:string; updatedAt:string };
export type DocumentRow = { id:string; userId:string; toolSlug:string; fileName:string; mimeType:string; sizeBytes:number; sha256:string; blobKey:string; blobIv:string; textKey:string; textIv:string; createdAt:string };
export type WorkflowRunRow = { id:string; userId:string; toolSlug:string; title:string; status:string; providerId:string; model:string; outputKey:string|null; outputIv:string|null; sourceCount:number; verifiedCitationCount:number; durationMs:number; inputTokens:number|null; outputTokens:number|null; errorCode:string|null; workflowVersion:string; approvedAt:string|null; approvedBy:string|null; createdAt:string; completedAt:string|null };

function visitor(r:Record<string,unknown>):VisitorRow { return { id:String(r.id), firstSeenAt:String(r.first_seen_at), lastSeenAt:String(r.last_seen_at), visitCount:Number(r.visit_count), guideCompletedAt:r.guide_completed_at?String(r.guide_completed_at):null, termsVersion:r.terms_version?String(r.terms_version):null, termsAcceptedAt:r.terms_accepted_at?String(r.terms_accepted_at):null }; }
function provider(r:Record<string,unknown>):ProviderRow { return { id:String(r.id),userId:String(r.user_id),label:String(r.label),provider:String(r.provider),model:String(r.model),baseUrl:String(r.base_url),apiKeyCiphertext:String(r.api_key_ciphertext),apiKeyIv:String(r.api_key_iv),createdAt:String(r.created_at),updatedAt:String(r.updated_at) }; }
function document(r:Record<string,unknown>):DocumentRow { return { id:String(r.id),userId:String(r.user_id),toolSlug:String(r.tool_slug),fileName:String(r.file_name),mimeType:String(r.mime_type),sizeBytes:Number(r.size_bytes),sha256:String(r.sha256),blobKey:String(r.blob_key),blobIv:String(r.blob_iv),textKey:String(r.text_key),textIv:String(r.text_iv),createdAt:String(r.created_at) }; }
function run(r:Record<string,unknown>):WorkflowRunRow { return { id:String(r.id),userId:String(r.user_id),toolSlug:String(r.tool_slug),title:String(r.title),status:String(r.status),providerId:String(r.provider_id),model:String(r.model),outputKey:r.output_key?String(r.output_key):null,outputIv:r.output_iv?String(r.output_iv):null,sourceCount:Number(r.source_count),verifiedCitationCount:Number(r.verified_citation_count),durationMs:Number(r.duration_ms),inputTokens:r.input_tokens==null?null:Number(r.input_tokens),outputTokens:r.output_tokens==null?null:Number(r.output_tokens),errorCode:r.error_code?String(r.error_code):null,workflowVersion:String(r.workflow_version),approvedAt:r.approved_at?String(r.approved_at):null,approvedBy:r.approved_by?String(r.approved_by):null,createdAt:String(r.created_at),completedAt:r.completed_at?String(r.completed_at):null }; }

export function touchVisitor(id:string, now:string):{row:VisitorRow;created:boolean} { const db=getDb(); const current=db.prepare("SELECT * FROM visitors WHERE id=?").get(id) as Record<string,unknown>|undefined; if(!current){db.prepare("INSERT INTO visitors (id,first_seen_at,last_seen_at,visit_count) VALUES (?,?,?,1)").run(id,now,now); return {row:visitor(db.prepare("SELECT * FROM visitors WHERE id=?").get(id) as Record<string,unknown>),created:true};} db.prepare("UPDATE visitors SET last_seen_at=?,visit_count=visit_count+1 WHERE id=?").run(now,id); return {row:visitor(db.prepare("SELECT * FROM visitors WHERE id=?").get(id) as Record<string,unknown>),created:false}; }
export function findVisitor(id:string):VisitorRow|null{const row=getDb().prepare("SELECT * FROM visitors WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?visitor(row):null;}
export function completeOnboarding(id:string,termsVersion:string,now:string):VisitorRow { const db=getDb(); db.prepare("UPDATE visitors SET guide_completed_at=?,terms_version=?,terms_accepted_at=?,last_seen_at=? WHERE id=?").run(now,termsVersion,now,now,id); const row=db.prepare("SELECT * FROM visitors WHERE id=?").get(id) as Record<string,unknown>|undefined; if(!row) throw new Error("SESSION_REQUIRED"); return visitor(row); }

export function listProviders(userId:string):ProviderRow[]{return (getDb().prepare("SELECT * FROM provider_configs WHERE user_id=? ORDER BY created_at DESC").all(userId) as Record<string,unknown>[]).map(provider);}
export function findProvider(userId:string,id:string):ProviderRow|null{const row=getDb().prepare("SELECT * FROM provider_configs WHERE id=? AND user_id=?").get(id,userId) as Record<string,unknown>|undefined;return row?provider(row):null;}
export function insertProvider(r:ProviderRow):void{getDb().prepare("INSERT INTO provider_configs (id,user_id,label,provider,model,base_url,api_key_ciphertext,api_key_iv,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(r.id,r.userId,r.label,r.provider,r.model,r.baseUrl,r.apiKeyCiphertext,r.apiKeyIv,r.createdAt,r.updatedAt);}
export function deleteProvider(userId:string,id:string):boolean{return Number(getDb().prepare("DELETE FROM provider_configs WHERE id=? AND user_id=?").run(id,userId).changes)>0;}

export function listDocuments(userId:string,toolSlug?:string|null):DocumentRow[]{const rows=toolSlug?getDb().prepare("SELECT * FROM documents WHERE user_id=? AND tool_slug=? ORDER BY created_at DESC").all(userId,toolSlug):getDb().prepare("SELECT * FROM documents WHERE user_id=? ORDER BY created_at DESC").all(userId);return (rows as Record<string,unknown>[]).map(document);}
export function findDocuments(userId:string,ids:string[]):DocumentRow[]{if(!ids.length)return[];const marks=ids.map(()=>"?").join(",");return (getDb().prepare(`SELECT * FROM documents WHERE user_id=? AND id IN (${marks})`).all(userId,...ids) as Record<string,unknown>[]).map(document);}
export function findDocument(userId:string,id:string):DocumentRow|null{const row=getDb().prepare("SELECT * FROM documents WHERE id=? AND user_id=?").get(id,userId) as Record<string,unknown>|undefined;return row?document(row):null;}
export function insertDocument(r:DocumentRow):void{getDb().prepare("INSERT INTO documents (id,user_id,tool_slug,file_name,mime_type,size_bytes,sha256,blob_key,blob_iv,text_key,text_iv,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").run(r.id,r.userId,r.toolSlug,r.fileName,r.mimeType,r.sizeBytes,r.sha256,r.blobKey,r.blobIv,r.textKey,r.textIv,r.createdAt);}
export function deleteDocument(userId:string,id:string):boolean{return Number(getDb().prepare("DELETE FROM documents WHERE id=? AND user_id=?").run(id,userId).changes)>0;}

export function insertRun(r:WorkflowRunRow):void{getDb().prepare("INSERT INTO workflow_runs (id,user_id,tool_slug,title,status,provider_id,model,output_key,output_iv,source_count,verified_citation_count,duration_ms,input_tokens,output_tokens,error_code,workflow_version,approved_at,approved_by,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(r.id,r.userId,r.toolSlug,r.title,r.status,r.providerId,r.model,r.outputKey,r.outputIv,r.sourceCount,r.verifiedCitationCount,r.durationMs,r.inputTokens,r.outputTokens,r.errorCode,r.workflowVersion,r.approvedAt,r.approvedBy,r.createdAt,r.completedAt);}
export function updateRunCompleted(id:string,userId:string,v:Pick<WorkflowRunRow,"outputKey"|"outputIv"|"verifiedCitationCount"|"durationMs"|"inputTokens"|"outputTokens"|"completedAt">):void{getDb().prepare("UPDATE workflow_runs SET status='completed',output_key=?,output_iv=?,verified_citation_count=?,duration_ms=?,input_tokens=?,output_tokens=?,completed_at=? WHERE id=? AND user_id=?").run(v.outputKey,v.outputIv,v.verifiedCitationCount,v.durationMs,v.inputTokens,v.outputTokens,v.completedAt,id,userId);}
export function updateRunFailed(id:string,userId:string,durationMs:number,completedAt:string):void{getDb().prepare("UPDATE workflow_runs SET status='failed',error_code='SAFE_FAILURE',duration_ms=?,completed_at=? WHERE id=? AND user_id=?").run(durationMs,completedAt,id,userId);}
export function listRuns(userId:string,toolSlug?:string|null):WorkflowRunRow[]{const rows=toolSlug?getDb().prepare("SELECT * FROM workflow_runs WHERE user_id=? AND tool_slug=? ORDER BY created_at DESC LIMIT 50").all(userId,toolSlug):getDb().prepare("SELECT * FROM workflow_runs WHERE user_id=? ORDER BY created_at DESC LIMIT 50").all(userId);return(rows as Record<string,unknown>[]).map(run);}
export function findRun(userId:string,id:string):WorkflowRunRow|null{const row=getDb().prepare("SELECT * FROM workflow_runs WHERE id=? AND user_id=?").get(id,userId) as Record<string,unknown>|undefined;return row?run(row):null;}
export function approveRun(userId:string,id:string,approvedBy:string,approvedAt:string):boolean{return Number(getDb().prepare("UPDATE workflow_runs SET approved_at=?,approved_by=? WHERE id=? AND user_id=? AND status='completed'").run(approvedAt,approvedBy,id,userId).changes)>0;}

export function listFirmConfigs(userId:string):Array<{kind:string;ciphertext:string;iv:string}>{return getDb().prepare("SELECT kind,ciphertext,iv FROM firm_configs WHERE user_id=?").all(userId) as Array<{kind:string;ciphertext:string;iv:string}>;}
export function upsertFirmConfig(userId:string,kind:string,ciphertext:string,iv:string,updatedAt:string):void{getDb().prepare("INSERT INTO firm_configs (user_id,kind,ciphertext,iv,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,kind) DO UPDATE SET ciphertext=excluded.ciphertext,iv=excluded.iv,updated_at=excluded.updated_at").run(userId,kind,ciphertext,iv,updatedAt);}
export function insertAuditEvent(r:{id:string;userId:string;runId:string|null;eventType:string;detail:string;createdAt:string}):void{getDb().prepare("INSERT INTO audit_events (id,user_id,run_id,event_type,detail,created_at) VALUES (?,?,?,?,?,?)").run(r.id,r.userId,r.runId,r.eventType,r.detail,r.createdAt);}
export function incrementRateLimit(userId:string,bucket:string,windowStart:number):number{const db=getDb();db.exec("BEGIN IMMEDIATE");try{const current=db.prepare("SELECT window_start,count FROM rate_limits WHERE user_id=? AND bucket=?").get(userId,bucket) as {window_start:number;count:number}|undefined;const count=current?.window_start===windowStart?Number(current.count)+1:1;db.prepare("INSERT INTO rate_limits (user_id,bucket,window_start,count) VALUES (?,?,?,?) ON CONFLICT(user_id,bucket) DO UPDATE SET window_start=excluded.window_start,count=excluded.count").run(userId,bucket,windowStart,count);db.exec("COMMIT");return count;}catch(error){db.exec("ROLLBACK");throw error;}}
